spring:
  application:
    name: playlist
    version: 1.0
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://playlist.cnlhntnhndr9.us-west-2.rds.amazonaws.com:3306/playList?serverTimezone=Asia/Seoul
    username: jiyani
    password: 1q2w3e4r!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      #hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true #쿼리를 가독성 있게 보여줌


http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

# log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



jwt:
  server:
    port: 8080
  secret: jwtsecretkey
